### ISSUE TITLE
Theme not being saved upon close/open

### ISSUE THREAD

**Issue by DragonFighter603** [Spydr06/logicrs#8] opened 2023-03-12 09:31 UTC
theme resets every time i open

**Comment by toadkarter** [comment] 2023-10-01 08:58
Hi there, I would be happy to take a look at this one if it's still available - if the issue could be assigned to me that would be great.

**Comment by Spydr06** [comment] 2023-10-01 09:10
sure, thanks for your interest!

**Comment by toadkarter** [comment] 2023-10-01 11:23
@Spydr06 Just wanted to check how you wanted to approach this. Basically the way I see it, this bug is caused by two issues: 
- There is currently no way to save a user config, and thus persist settings between sessions; and
- the GAction for changing the theme is currently automatically initialised on start up with "System Preferences" by default. 

For each of the issues I would propose the following:

**Saving**

I think it should be straightforward enough to add some sort of json / yml config file with the relevant enum that the user wishes to choose for their theme. 

I think you are using some form of json for the saved layouts so I think it makes sense to continue using json here? Also, just wanted to check if you had a preference as to where this config should be saved - maybe at the root of the install. 

**Loading**

This one is a little trickier because the logic for selecting a theme is quite closely coupled with the UI code (i.e., gaction_change_theme takes in a SimpleAction parameter and is initialised with default values in the ACTIONS array). 

What we can do is extract some of the logic from "gaction_change_theme" into a more generic function called "change_theme", and have "gaction_change_theme" call this - then, in the intialise method of "Application" we can call "change_theme" without having to pass in a SimpleAction, which as far as  I can see is a UI specific thing. 

The only question remains for me is where the UI value is initialised - because I have tried doing this locally with a hard-coded value and while the theme did change, the UI dropdown was still set to "System Preference". If you could let me know where in the code I could go to change this that would be much appreciated! 

Let me know if you are happy with the above approach and I can get cracking on it!

**Comment by Spydr06** [comment] 2023-10-01 11:38
Yes that's how I'd implement it too it too
- Saving: `json` sounds good, since we're, as you already noticed, using it for the `.lrsproj` and `.lrsmod` files. `toml`, which is the Rust-default for stuff like this might be a little sleeker (?), but I think `json` is perfectly fine.
- Loading: you have to change the default value [in this line](https://github.com/Spydr06/logicrs/blob/ca5f26078e1e89bd39b3f160c854e818e731b8c1/src/application/gactions.rs#L104C18-L104C18), this changes the initial button state.

**Comment by toadkarter** [comment] 2023-10-01 18:56
Apols for the late reply - yes that all sounds good, I'm working away at it now :)

**Comment by Spydr06** [comment] 2023-10-01 19:16
@toadkarter awesome, I'm looking forward to it. Have fun :D

**Comment by Spydr06** [comment] 2023-10-05 10:49
1. The standard field in `ACTIONS` only affects the button state, you have to change the theme itself separately. The theme is "System Preference" by default with `ibadwaita`.

2. Since `ACTIONS` is `lazy_static!`, this means that it is only evaluated once it's actually used **at runtime**. This way you can add whatever function you want to get the initial button state (that's what I meant with "callback"). But `setup_gactions` isn't a bad place either.

**Comment by toadkarter** [comment] 2023-10-05 18:11
Excellent, thanks! I will give this a go now

**Closed** 2023-10-09 16:56 UTC
Labels: ui-bug, hacktoberfest
